<%doc>
Template used by `alembic revision` to generate every new migration
file. Kept close to Alembic's stock template, with one addition: a
standing reminder comment at the top of every generated file, since
autogenerate is a starting point, not a guarantee — it can miss
data-migration logic, some constraint changes, and anything that isn't
a pure structural diff.
</%doc>"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

NOTE: If this migration was autogenerated, review it before applying —
autogenerate detects structural (table/column/constraint) differences
reliably, but does not detect data migrations, some constraint-only
changes, or renames (it will see a rename as a drop + add unless
adjusted by hand).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
