import React, { useEffect, useState } from 'react';
import { createPrediction, getPredictionHistory } from '../../api/predictions';
import { PredictionResponse, PredictionResponseWithID } from '../../types/prediction';
import { getSearchId, getSelectedFlight, getSearchFlights } from '../../utils/workspace';

const PredictionsPage: React.FC = () => {
  const [prediction, setPrediction] = useState<PredictionResponse | null>(null);
  const [history, setHistory] = useState<PredictionResponseWithID[]>([]);
  const [loading, setLoading] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const flight = getSelectedFlight() || getSearchFlights()[0];
  useEffect(() => { getPredictionHistory().then(setHistory).catch((err) => { setHistory([]); setError(err instanceof Error ? err.message : 'Unable to load prediction history.'); }).finally(() => setHistoryLoading(false)); }, []);
  const predict = async () => { if (!flight || !getSearchId()) { setError('Run a flight search and select a result before requesting a prediction.'); return; } setLoading(true); setError(null); try { const departure = new Date(flight.departure_time); const arrival = new Date(flight.arrival_time); setPrediction(await createPrediction({ origin: flight.origin, destination: flight.destination, departure_date: departure.toISOString(), passengers: 1, cabin_class: 'ECONOMY', currency: flight.currency, airline: flight.airline, flight_number: flight.flight_number, departure_time: departure.toISOString().slice(11, 16), arrival_time: arrival.toISOString().slice(11, 16), duration_minutes: flight.duration, stops: flight.stops }, getSearchId()!)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create a prediction.'); } finally { setLoading(false); } };

  return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">Price intelligence</span><h1 className="page-title">Read the price signal.</h1><p className="page-subtitle">Generate a model-backed price estimate for a flight from your latest search.</p></div><span className="badge">Model insight</span></header><section className="surface surface-pad"><div className="results-head"><div><h2 className="section-title">{flight ? `${flight.origin} → ${flight.destination}` : 'No flight selected'}</h2><p className="section-note">{flight ? `${flight.airline} ${flight.flight_number} · Current price ${flight.currency} ${flight.price.toFixed(2)}` : 'Select a flight from the search page to begin.'}</p></div><button className="btn btn-primary" type="button" onClick={predict} disabled={loading || !flight}>{loading ? 'Analyzing...' : 'Predict price →'}</button></div>{error && <div className="auth-error" style={{ marginTop: 18 }} role="alert">{error}</div>}{prediction && <div className="quick-grid" style={{ marginTop: 24 }}><div className="quick-card"><span className="eyebrow">Predicted price</span><strong className="price">{prediction.currency} {prediction.predicted_price.toFixed(2)}</strong><span>{prediction.is_estimate ? 'Model estimate' : 'Prediction'}</span></div><div className="quick-card"><span className="eyebrow">Model version</span><strong>{prediction.model_version}</strong><span>Used for this estimate</span></div></div>}</section><section className="surface surface-pad"><div className="results-head"><div><h2 className="section-title">Prediction history</h2><p className="section-note">Previous estimates returned for your account.</p></div></div>{historyLoading ? <div className="skeleton" style={{ marginTop: 20 }} /> : history.length === 0 ? <div className="empty-state" style={{ padding: '34px 10px' }}><h3>No predictions yet</h3><p>Generate a prediction from a recent flight search.</p></div> : <div className="capability-list">{history.map((item) => <div className="capability" key={item.id}><span className="capability-mark">✦</span><div><strong>{item.currency} {item.predicted_price.toFixed(2)}</strong><span>{new Date(item.created_at).toLocaleString()} · model {item.model_version}</span></div></div>)}</div>}</section></div>;
};

export default PredictionsPage;
