"""enable pgvector extension

Revision ID: 0001
Revises:
Create Date: 2026-08-01

This is the project's first migration, hand-written rather than
autogenerated — there are no ORM models yet (they're added in a later
implementation phase), so there is nothing for `--autogenerate` to
diff. Its only job is to guarantee the `vector` extension exists before
any later migration adds a pgvector column.

This is deliberately redundant with the startup-time check in
app/infrastructure/vector/extension.py, not a replacement for it: the
startup check covers "the running app connects to a database that
hasn't been migrated yet" during early development; this migration
covers "a database provisioned purely via `alembic upgrade head`" (e.g.
in CI, or a fresh production database that never went through an
application startup cycle). Both must independently guarantee the same
end state.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    # Only dropped on downgrade if nothing else depends on it. In
    # practice this migration is never downgraded past in a real
    # environment once any vector column exists — Postgres will refuse
    # to drop an extension a column still depends on, which is the
    # correct, safe failure mode here rather than something to work
    # around.
    op.execute("DROP EXTENSION IF EXISTS vector")
