"""create users table

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-02

Hand-written rather than autogenerated (consistent with 0001) — this
environment has no live database to autogenerate against. Every column,
constraint, and index below was verified beforehand by compiling
UserModel's DDL against the real PostgreSQL dialect (no live connection
needed for that step), so this migration matches the model exactly
rather than being hand-typed from memory.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_status_enum = sa.Enum("active", "inactive", name="user_status")


def upgrade() -> None:
    # No explicit user_status_enum.create() call here: op.create_table
    # below already creates the column's Enum type as a dependency
    # automatically — calling .create() separately duplicated the
    # `CREATE TYPE user_status` statement (verified via `alembic
    # upgrade head --sql`, which is exactly how this was caught).
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("google_sub_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            user_status_enum,
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("google_sub_id", name="uq_users_google_sub_id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    user_status_enum.drop(op.get_bind(), checkfirst=True)
