"""Add min_price and max_price to preference model

Revision ID: e99b7797d4b3
Revises: e1fb3efa5490
Create Date: 2026-08-30 14:26:39.816836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99b7797d4b3'
down_revision: Union[str, None] = 'e1fb3efa5490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('min_price', sa.Float(), nullable=True))
    op.add_column('preferences', sa.Column('max_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'max_price')
    op.drop_column('preferences', 'min_price')
    # ### end Alembic commands ###
