artifact_location: file:///D:/AI_Flight%20_intelligence/AI_Flight_Intelligence/ml/mlflow_tracking/554789444325111316
creation_time: 1786616006201
experiment_id: '554789444325111316'
last_update_time: 1786616006201
lifecycle_stage: active
name: flight_price_prediction
