artifact_location: file:///D:/AI_Flight%20_intelligence/AI_Flight_Intelligence/ml/mlflow_tracking/0
creation_time: 1786616006183
experiment_id: '0'
last_update_time: 1786616006183
lifecycle_stage: active
name: Default
